# Generated by Django 4.0.2 on 2022-02-17 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=255)),
                ('value_date', models.DateField()),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('account_number', 'date'),
            },
        ),
    ]
